name: "Daniel Connelly"
highlighter: rouge
permalink: :title
exclude: [README.md, LICENSE, Makefile]
baseurl: ''

# Information for the Atom feed
dhconnelly:
   author: "Daniel Connelly"
   email: "dhconnelly@gmail.com"
